name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "3 1 * * 3"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.1.3
        id: go
        with:
          stable: false
          go-version: 1.x

      - uses: actions/checkout@v2.3.4

      - name: install gotip
        run: |
          go install golang.org/dl/gotip
          gotip download

      - name: run-tests
        run: gotip test -gcflags=-G=3
